---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hubble-timescape
  namespace: kube-system
spec:
  interval: 2m
  chart:
    spec:
      chart: hubble-timescape
      version: x
      sourceRef:
        kind: HelmRepository
        name: isovalent
        namespace: kube-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    clickhouse:
      cluster:
        enabled: true
        volumes:
          data:
            size: 5Gi
            # storageClassName: ""
    ingester:
      bucket:
        uri: "file:///path/to/data"
      