---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hubble-timescape
  namespace: kube-system
spec:
  interval: 2m
  chart:
    spec:
      chart: hubble-timescape
      version: x
      sourceRef:
        kind: HelmRepository
        name: isovalent
        namespace: kube-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    clickhouse:
      cluster:
        enabled: true
        prometheus:
          serviceMonitor:
            enabled: true
        volumes:
          data:
            size: 1Gi
    server:
      prometheus:
        enabled: true
        serviceMonitor:
          enabled: true
    ingester:
      prometheus:
        enabled: true
        serviceMonitor:
          enabled: true
      bucket:
        uri: "s3://timescape?endpoint=http://minio.minio.svc.cluster.local:80&s3ForcePathStyle=true"
        prefixPattern: "hubble-events/%Y/%m/%d/"
    grafana:
      dashboards:
        enabled: true
        labels:
          grafana_dashboard: "1"
        namespace: monitoring