apiVersion: v1
kind: Secret
metadata:
  name: hubble-timescape-ingester-creds
  namespace: hubble-timescape
type: Opaque
stringData:
  CLICKHOUSE_PASSWORD: password
---
apiVersion: v1
kind: Secret
metadata:
  name: hubble-timescape-migrate-creds
  namespace: hubble-timescape
type: Opaque
stringData:
  CLICKHOUSE_PASSWORD: password
---
apiVersion: v1
kind: Secret
metadata:
  name: hubble-timescape-server-creds
  namespace: hubble-timescape
type: Opaque
stringData:
  CLICKHOUSE_PASSWORD: password