---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: monitoring
spec:
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: kube-prometheus-stack
      version: x
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
  values:
    grafana:
      admin:
        existingSecret: "grafana"
        passwordKey: admin
        userKey: admin
      dashboards:
        default:
          flux2:
            gnetId: 16714
            revision: 1
            datasource: Prometheus
    alertmanager:
      enabled: false
    prometheus:
      prometheusSpec:
        retention: 24h
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
        podMonitorNamespaceSelector: {}
        podMonitorSelector:
          matchLabels:
            app.kubernetes.io/component: monitoring
