apiVersion: v1
kind: Secret
metadata:
  name: hubble-timescape-ingester-creds
  namespace: hubble-timescape
type: Opaque
stringData:
  CLICKHOUSE_PASSWORD: password
  AWS_ACCESS_KEY_ID: minio
  AWS_SECRET_ACCESS_KEY: quickstart
  AWS_DEFAULT_REGION: dummy
---
apiVersion: v1
kind: Secret
metadata:
  name: hubble-timescape-migrate-creds
  namespace: hubble-timescape
type: Opaque
stringData:
  CLICKHOUSE_PASSWORD: password
---
apiVersion: v1
kind: Secret
metadata:
  name: hubble-timescape-server-creds
  namespace: hubble-timescape
type: Opaque
stringData:
  CLICKHOUSE_PASSWORD: password
---
apiVersion: v1
kind: Secret
metadata:
  name: hubble-timescape-trimmer-creds
  namespace: hubble-timescape
type: Opaque
stringData:
  CLICKHOUSE_PASSWORD: password