apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tenant
spec:
  chart:
    spec:
      chart: tenant
      version: 6.0.1
      sourceRef:
        kind: HelmRepository
        name: minio-operator
        namespace: minio-operator
  values:
    secrets:
      enabled: true
      name: minio-secret
      accessKey: minio
      secretKey: quickstart
    tenant:
      name: quickstart
      configuration:
        name: minio-secret
      image:
        repository: minio/minio
        tag: RELEASE.2023-06-16T02-41-06Z
        pullPolicy: IfNotPresent
      pools:
        - servers: 1
          volumesPerServer: 4
          name: "quickstart"
          size: 2Gi
          #storageClassName: ebs-sc
      buckets:
        - name: "timescape"
      certificate:
        requestAutoCert: false
      kes:
        configuration: false
      log:
        disabled: true
      prometheus:
        disabled: true
