apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: operator
spec:
  releaseName: operator
  targetNamespace: minio-operator

  chart:
    spec:
      chart: operator
      version: 6.0.1
      sourceRef:
        kind: HelmRepository
        name: minio-operator
  interval: 10m0s
  values:
