apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: operator
spec:
  releaseName: operator
  targetNamespace: minio-operator
  interval: 2m
  chart:
    spec:
      chart: operator
      version: 6.0.1
      sourceRef:
        kind: HelmRepository
        name: minio-operator
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values: