---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium-dnsproxy
  namespace: kube-system
spec:
  chart:
    spec:
      chart: cilium-dnsproxy
      version: 1.15.7
      sourceRef:
        kind: HelmRepository
        name: isovalent
  interval: 10m0s
  values:
