---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium-dnsproxy
  namespace: kube-system
spec:
  interval: 2m
  chart:
    spec:
      chart: cilium-dnsproxy
      version: 1.15.7
      sourceRef:
        kind: HelmRepository
        name: isovalent
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
