---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  chart:
    spec:
      chart: cilium
      version: 1.15.7
      sourceRef:
        kind: HelmRepository
        name: isovalent
  interval: 10m0s
  values:
    prometheus:
      enabled: true
    operator:
      replicas: 1
      prometheus:
        enabled: true
    bgpControlPlane:
      enabled: true
    ipv4:
      enabled: true
    ipv4NativeRoutingCIDR: 10.42.0.0/16
    ipv6:
      enabled: false
    k8s-require-ipv4-pod-cidr: true
    kubeProxyReplacement: true
    ipam:
      mode: kubernetes
    tunnel: vxlan
    externalIPs:
      enabled: true
    hostPort:
      enabled: true
    hostServices:
      enabled: false
    envoy:
      enabled: true
    envoyConfig:
      enabled: true
    loadBalancer:
      l7:
        backend: envoy
    egressGateway:
      enabled: true
    bpf:
      masquerade: true
    routingMode: tunnel
    tunnelProtocol: vxlan
    extraConfig:
      external-dns-proxy: "true"
      export-file-path: ""
    hostFirewall:
      enabled: true
    hubble:
      enabled: true
      relay:
        enabled: true
      tls:
        enabled: true
      metrics:
        enabled:
          - flow_export
