---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hubble-ui
  namespace: kube-system
spec:
  chart:
    spec:
      chart: hubble-ui
      version: x
      sourceRef:
        kind: HelmRepository
        name: isovalent
  interval: 10m0s
  values:
    serviceAccount:
      create: true
      name: hubble-ui
      annotations: {}
    rollOutPods: true
    timescape:
      enabled: true
    # grafana:
    #   createConfigMaps: true
    #   enabled: true
    #   enabledNodesGraph: true
