---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hubble-ui
  namespace: kube-system
spec:
  chart:
    spec:
      chart: hubble-ui
      version: x
      sourceRef:
        kind: HelmRepository
        name: isovalent
  interval: 10m0s
  values:
    timescape:
      enabled: true
      address: "hubble-timescape.hubble-timescape"
    grafana:
      enabled: true
      enabledNodesGraph: true
      namespace: "monitoring"
