---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hubble-timescape
  namespace: kube-system
spec:
  interval: 2m
  chart:
    spec:
      chart: hubble-timescape
      version: x
      sourceRef:
        kind: HelmRepository
        name: isovalent
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    serviceAccount:
      create: true
      name: hubble-ui
      annotations: {}
    rollOutPods: true
    timescape:
      enabled: true