apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - cilium.yaml
  - cilium-dnsproxy.yaml
  - hubble-enterprise.yaml
  - hubble-ui.yaml  
  - tetragon.yaml
  - helm-repository.yaml
  - hubble-timescape.yaml