apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tetragon
  namespace: kube-system
spec:
  interval: 2m
  chart:
    spec:
      chart: tetragon
      version: x
      sourceRef:
        kind: HelmRepository
        name: isovalent
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    tetragon:
      btf: /sys/kernel/btf/vmlinux
      enabled: true
      # grpc:
      #   address: localhost:54321
      #   enabled: false
    exportDirectory: "/var/run/cilium/hubble"
