apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tetragon
  namespace: kube-system
spec:
  chart:
    spec:
      chart: tetragon
      version: x
      sourceRef:
        kind: HelmRepository
        name: isovalent
  values:
    tetragon:
      btf: /sys/kernel/btf/vmlinux
      enabled: true
      prometheus:
        enabled: true
        port: 2112
        serviceMonitor:
          enabled: true
    exportDirectory: "/var/run/cilium/hubble"
