apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: clickhouse-operator
  namespace: kube-system
spec:
  chart:
    spec:
      chart: altinity-clickhouse-operator
      version: 0.22.0
      sourceRef:
        kind: HelmRepository
        name: altinity
  interval: 10m0s
  values:
    operator:
      env:
        - name: WATCH_NAMESPACES
          value: hubble-timescape
