apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: clickhouse-operator
  namespace: kube-system
spec:
  interval: 2m
  chart:
    spec:
      chart: clickhouse-operator
      version: x
      sourceRef:
        kind: HelmRepository
        name: altinity
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    operator:
      env:
        - name: WATCH_NAMESPACES
          value: hubble-timescape