apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cilium
  labels:
    app.kubernetes.io/part-of: flux
    app.kubernetes.io/component: monitoring
spec:
  namespaceSelector:
    matchNames:
      - "kube-system"
  selector:
    matchLabels:
      app.kubernetes.io/part-of: "cilium"
  podMetricsEndpoints:
    - port: "prometheus"
      interval: "30s"
      honorLabels: true